### PR TITLE
added students solution to review

### PR DESCRIPTION
**Pull request by mark405**

### CODE REVIEW

File: src/main/java/core/basesyntax/Ball.java [hunk 1]
```diff
@@ -0,0 +1,35 @@
+package core.basesyntax;
+
+public class Ball {
+    String ballColor;
```
Comment (mark405) [inline src/main/java/core/basesyntax/Ball.java:4]: Fields as classes, constructors and methods must have access modifiers.
Default modifiers are bad practice.

File: src/main/java/core/basesyntax/Ball.java [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+    int ballNumber;
```
Comment (mark405) [inline src/main/java/core/basesyntax/Ball.java:5]: Fields as classes, constructors and methods must have access modifiers.
Default modifiers are bad practice.

File: src/main/java/core/basesyntax/Ball.java [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+    public int getBallNumber() {
+        return this.ballNumber;
+    }
+
+    public void setBallNumber(int ballNumber) {
+        this.ballNumber = ballNumber;
+    }
+
+    public String toString() {
+        String ball = "ball";
```
Comment (mark405) [inline src/main/java/core/basesyntax/Ball.java:32]: Don't create variables that are never used

File: src/main/java/core/basesyntax/Ball.java [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+
+    public int getBallNumber() {
+        return this.ballNumber;
+    }
+
+    public void setBallNumber(int ballNumber) {
+        this.ballNumber = ballNumber;
+    }
+
+    public String toString() {
```
Comment (mark405) [inline src/main/java/core/basesyntax/Ball.java:31]: No Override annotation. It may cause a compilation error if you signature doesn't match the method it's supposed to override.
https://mate-academy.github.io/style-guides/java/java.html#s6.1-override-annotation

File: src/main/java/core/basesyntax/ColorSupplier.java [hunk 5]
```diff
@@ -1,7 +1,12 @@
 package core.basesyntax;
 
+import java.util.Random;
+
 public class ColorSupplier {
-    public String getRandomColor() {
-        return null;
+
+
+    public static String getRandomColor() {
```
Comment (mark405) [inline src/main/java/core/basesyntax/ColorSupplier.java:8]: Static methods are commonly bad practice.
It is better to create instance and call needed method.

File: src/main/java/core/basesyntax/ColorSupplier.java [hunk 6]
```diff
@@ -1,7 +1,12 @@
...
+        int index = new Random().nextInt(Colors.values().length);
```
Comment (mark405) [inline src/main/java/core/basesyntax/ColorSupplier.java:9]: It is better to check if empty array or not otherwise It will cause ArrayIndexOutOfBoundException

File: src/main/java/core/basesyntax/ColorSupplier.java [hunk 7]
```diff
@@ -1,7 +1,12 @@
...
+        return Colors.values()[index].toString();
```
Comment (mark405) [inline src/main/java/core/basesyntax/ColorSupplier.java:10]: Good practice is to call name() method of enum class to get string representation.
toString() is common for all enum constants

File: src/main/java/core/basesyntax/ColorSupplier.java [hunk 8]
```diff
@@ -1,7 +1,12 @@
 package core.basesyntax;
 
+import java.util.Random;
+
 public class ColorSupplier {
-    public String getRandomColor() {
-        return null;
+
```
Comment (mark405) [inline src/main/java/core/basesyntax/ColorSupplier.java:6]: It is bad practice to add redundant empty lines after class declarations or method signatures.

File: src/main/java/core/basesyntax/Colors.java [hunk 9]
```diff
@@ -0,0 +1,8 @@
+package core.basesyntax;
+
+public enum Colors {
+    black,
```
Comment (mark405) [inline src/main/java/core/basesyntax/Colors.java:4]: https://mate-academy.github.io/style-guides/java/java.html#s5.2.4-constant-names
Constants should use CONSTANT_CASE

File: src/main/java/core/basesyntax/Lottery.java [hunk 10]
```diff
@@ -0,0 +1,16 @@
+package core.basesyntax;
+
+import java.util.Random;
+
+public class Lottery extends ColorSupplier {
```
Comment (mark405) [inline src/main/java/core/basesyntax/Lottery.java:5]: No need to to extend ColorSupplier class. Inheritance is typically used when there is an "is-a" relationship between the base class and the subclass. ColorSupplier is not a Lottery.
Better to create instance of ColorSupplier and call it's methods

File: src/main/java/core/basesyntax/Lottery.java [hunk 11]
```diff
@@ -0,0 +1,16 @@
...
+    public Ball getRandomBall() {
+
+        Ball ball = new Ball();
+
+        ball.setBallColor(ColorSupplier.getRandomColor());
```
Comment (mark405) [inline src/main/java/core/basesyntax/Lottery.java:10]: Static methods are commonly bad practice.
It is better to create instance and call needed method.

File: src/main/java/core/basesyntax/Lottery.java [hunk 12]
```diff
@@ -0,0 +1,16 @@
+package core.basesyntax;
+
+import java.util.Random;
+
+public class Lottery extends ColorSupplier {
+    public Ball getRandomBall() {
+
```
Comment (mark405) [inline src/main/java/core/basesyntax/Lottery.java:7]: Avoid redundant empty lines

File: src/main/java/core/basesyntax/Lottery.java [hunk 13]
```diff
@@ -0,0 +1,16 @@
...
+        Ball ball = new Ball();
+
+        ball.setBallColor(ColorSupplier.getRandomColor());
+
+        ball.setBallNumber(new Random().nextInt(100));
```
Comment (mark405) [inline src/main/java/core/basesyntax/Lottery.java:12]: Magic numbers should be constants.

File: src/main/java/core/basesyntax/Application.java [hunk 14]
```diff
@@ -2,6 +2,11 @@
 
 public class Application {
     public static void main(String[] args) {
-        // create three balls using class Lottery and print information about them in console
+        Lottery ball1 = new Lottery();
```
Comment (mark405) [inline src/main/java/core/basesyntax/Application.java:5]: No need to create several instances of class Lottery.
Lottery has its method  that gives random ball every time it is called.
Lottery instance is not a ball and should be renamed.
